owner: lryong # GitHub username
repo: upptime # GitHub repository name
sites: # List of endpoints to track
  - name: Herbert's Blog
    url: http://www.herbert.top:18080
assignees: # Users to assign downtime issues (optional)
  - lryong
status-website:
  baseUrl: /upptime # where "repo" is your repository name
  name: Upptime Status Monitor
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  introTitle: "Herbert's Blog Website's Uptime **Monitor**"
  introMessage: Good good study, day day up~
