owner: lryong # GitHub username
repo: upptime # GitHub repository name
sites: # List of endpoints to track
  - name: Herbert's Blog
    url: https://blog.herbert.top
assignees: # Users to assign downtime issues (optional)
  - lryong
status-website:
  baseUrl: /upptime # where "repo" is your repository name
  name: Upptime Status Monitor
